---

- hosts: web
  tasks:
  - name: Install apache2 package
    apt:
      name: apache2
      state: latest
  - name: check apache2 service status
    service:
      name: apache2
      state: started
